### PR TITLE
Math Magicians - Calculator Events

### PR DESCRIPTION
**Pull request by mwismann**
### Math Magicians - Calculator Events 😎 
**The following changes were implemented:**

- Created a new directory called ``logic`` inside the project ✅ 
- Copied the files ``calculate.js`` and ``operate.js`` into the ``logic/`` directory ✅ 
- Installed [big.js](https://www.npmjs.com/package/big.js) using ``npm`` ✅ 
- Implemented click event handlers using the math logic from ``calculate.js`` and ``operate.js`` in the React component ✅ 
- The ``Calculator`` is able to perform math operations✅
- The operations and results are properly displayed ✅

### CODE REVIEW

**Review by franclobo — COMMENTED** [review]
Hi @mwismann, 

terminator

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that doesn't have a professional README file. All main headers from the [README template](https://github.com/microverseinc/readme-template) should be present in your repo, it includes the Live demo section 👇🏽 

| Expected | Your README |
|---|---|
| image | image |



Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by mwismann** [comment]
> 

Hi @franclobo,

Thank you for getting back to me so quickly. I removed the live demo because my first reviewer for Monday's milestone asked me to 😓. She suggested removing it per Microverse's new requirements and adding it after I have a deployed live demo.

Nevertheless, I'll add it again.

Once again, thank you for the kind feedback!

**Comment by franclobo** [comment]
> > 
> 
> Hi @franclobo,
> 
> Thank you for getting back to me so quickly. I removed the live demo because my first reviewer for Monday's milestone asked me to 😓. She suggested removing it per Microverse's new requirements and adding it after I have a deployed live demo.
> 
> Nevertheless, I'll add it again.
> 
> Once again, thank you for the kind feedback!

Hi @mwismann the requirement is unless you have deployed yet the application you should replace the link with the "Coming soon..." phrase. 👍🏽

**Review by anagudelogu — APPROVED** [review]
# STATUS: APPROVED! 🍾 🎆 🥇 

Hi @mwismann, 
I'm Andres.

You did a great job working on this milestone, your project is complete! 🚀 
There is nothing else to say other than... it's time to merge it 🤖  
Congratulations! 🎉 



## Highlights
✅ Great use of Git flow. 💯 
✅ Your project is documented professionally. 📜 
✅ Descriptive PR title, summary and commit messages. 💬 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
